### ISSUE TITLE
Add support for/in FullCalendar views module

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/repeating_dates#11]
While views works with list / grid options in displaying the multiple values, it doesn't work with calendar views.  The only one I can see (fullcalendar) gives the message:
Display "Block" requires at least one date field.

**Comment by indigoxela** [comment]
> Add formatter that works with Calendar View

I'm trying to understand: is this about the lack of support for this field type in the FullCalendar (views) module?
Or is this about a single field's value display as FullCalendar?

Maybe I should rephrase my question... :wink: 

**Where** would you like to display the recurring dates in a Javascript calendar?

- As field along with the node, per node
- Combined with other date fields in a view (like a site-wide overview)

**Comment by yorkshire-pudding** [comment]
@indigoxela - the latter Combined with other date fields in a view (like a site-wide overview)

Lets say I have a mix of recurring events and one-off events - these would all be able to display on the same calendar.

**Comment by indigoxela** [comment]
> the latter Combined with other date fields in a view (like a site-wide overview)

That's tricky, because it's the Fullcalendar module, that will need changes to support this new field type. I don't think, this module could accomplish that without the other module.

**Comment by yorkshire-pudding** [comment]
OK. Thanks anyway

**Comment by indigoxela** [comment]
Hey, you're giving up fast... :smirk:

Maybe it's feasible - not sure how the Fullcalendar module does it, but eventually its maintainer is also interested.

**Comment by indigoxela** [comment]
Not directly related but struggling with a similar problem: https://github.com/backdrop-contrib/fullcalendar/issues/7

@laryn did you ever get anywhere near to a solution for additional (other non-core date) fields?

**Comment by laryn** [comment]
@indigoxela No, that issue didn't get any further (yet).

**Comment by indigoxela** [comment]
Hm, seems like the date field db column names are sort of hardcoded in the date views handlers. To my understanding this means, no other field type will ever work with that module, although views itself could handle them. (The date field module does a lot of odd stuff.)

**Comment by yorkshire-pudding** [comment]
Is the issue within the fullcalendar module or within the date field (core) module.  Am I right in thinking that the reason date based modules are less common in b than d7 is down to Chaos tools?  I note that on the d7 site I have that has a calendar, it requires Views, Chaos tools, Date API, and Date Views.  Date Views also uses Views, Chaos tools, Date API.

Perhaps it's not so critical to use a calendar - certainly on mobile, list formats work best. I wasn't giving up per se, but more thinking the issue needs to be in fullcalendar.

**Comment by indigoxela** [comment]
> Is the issue within the fullcalendar module or within the date field (core) module.

I think the limitation is in both.

As Date Repeat (contrib) is IMO unportable (hackish stuff has been removed from the date field module before it went into core, so that date_repeat stub can't work anymore), I came up with a completely new field type. Same as D8, BTW, with their date_recur module.

Date views with Fullcalendar in Drupal 7 (not sure about D8/9) also only handle values provided by _date fields_, nothing else - correct me if I'm wrong.

I see no problem in displaying repeating_dates in a Javascript calendar, but currently there's no module for that yet, so it requires a little bit of coding.

> Am I right in thinking that the reason date based modules are less common in b than d7 is down to Chaos tools?

I see no evidence for that. 
Ctools is just a removed abstraction layer, that's not needed anymore.

**Comment by yorkshire-pudding** [comment]
It was https://www.drupal.org/project/calendar I used in Drupal

**Comment by indigoxela** [comment]
Hm, Calendar is a completely different module. It has no release for B yet, and I'm not sure if it ever will get one. Personally, I haven't used that one in years with Drupal and wouldn't with Backdrop - way too old-fashioned.

**Comment by yorkshire-pudding** [comment]
Aye - looks like its dead in the water (https://github.com/backdrop-contrib/calendar)

**Comment by indigoxela** [comment]
As the initial request (FullCalendar Views support) turned out to be impossible, and the Calendar module probably won't ever get a stable release, I'm closing this as "won't fix". Alternate solutions are possible, but are out of the scope of this module. I assume, this needs a completely new module.
