### ISSUE TITLE
Can't save content

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/repeating_dates#3]
When I've added a Repeating Date to a content type, it isn't allowing me to save the content. 

- If I have a recurring option set to "Daily every 1 day / Stop after 10" it tells me to change the "Stop after X" value to no more than 1 recurrence.
- If I choose "Do not repeat" the Submit button just does nothing. (Side note: the "Exclude dates" details element could hide if "Do not repeat" is chosen.

**Comment by laryn** [comment]
I see now that the "Stop after X" value is tied to the field cardinality, which wasn't clear to me. The default value of 10 should also be tied to that value, and perhaps a description on that widget to indicate where the limit is coming from?

https://github.com/backdrop-contrib/repeating_dates/blob/f883f3b5670b60c4ac9d84d24e28803df4940136/repeating_dates.widget_form.inc#L333-L351

**Comment by laryn** [comment]
After fixing this cardinality issue on the field settings, I can click Save -- but no data seems to actually save.

**Comment by indigoxela** [comment]
Yes, it's all a bit rough around the edges, one of the many todos is to add more field settings and some help text to explain, what to configure. :wink:

> but no data seems to actually save.

Something in dblog? If nothing saves, either the field was considered empty (needs a start date), or an exception occurred - which should show up in dblog (and only there, because of try/catch).

**Comment by indigoxela** [comment]
Regarding cardinality... could it make sense to display a warning message, when opening the node form, in case the cardinality is extremely low? For instance, less then 5?

When adding new fields the cardinality is 1 by default - with a message we could prevent a typical WTF moment...

**Comment by olafgrabienski** [comment]
> Regarding cardinality... could it make sense to display a warning message, when opening the node form, in case the cardinality is extremely low? For instance, less then 5?

I've just installed the module and found the message on the node form helpful. Maybe speak of "Number of values" instead of just max values? (e.g. `The "Number of values" setting in the field %field is very low. ...`)

In my opinion, a message on the *field configuration* form (with a hint to the collapsed "Global settings" section where the "Number of values" setting lives) would also be very helpful.

**Comment by olafgrabienski** [comment]
> After fixing this cardinality issue on the field settings, I can click Save -- but no data seems to actually save.

I have a similar issue when trying to save a weekly event.

- Choose date and times as "Start" and "To" date.
- Don't change "Repeats Weekly" and "Every 1 week".
- Weekdays: choose the same day as in Date and times (in my case "Mon")
- Don't change Stop "based on Count" and "after 10 recurrences".

When I save the node form, I don't see a result on the page (node view). Editing the node again, I see empty date inputs.

There is a message in DBlog:

> InvalidArgumentException: Invalid BYDAY value: 1 in RRule\RRule->__construct() (line 335 of /path-to-backdrop/modules/repeating_dates-1.x-1.x/libraries/php-rrule/src/RRule.php).

The exact `Invalid BYDAY value` seems to depend on which weekday I chose. I wasn't however able to figure out a weekday where it works.

**Comment by indigoxela** [comment]
> Invalid BYDAY value: 1

It shouldn't be a number, it's supposed to be a string like "MO".

Nice catch! This only happens, if the first day of week is set to "Sunday" - the default in the system regional settings.
